language: generic

php:
  - '7.0'

node_js:
  - '10'

before_script:
  - curl -sL http://getcomposer.org/installer | php

script:
  - cd php; composer create-project
  - cd nodejs; npm i && npm build

notifications:
  email: false